### ISSUE TITLE
Files mentioned in Manhattan - SUMO Documentation not found

### ISSUE THREAD

**Issue by Enough7** [eclipse/sumo.website#3]
[Manhattan - SUMO Documentation](https://sumo.dlr.de/docs/Tutorials/Manhattan.html) says _All files can also be found in the <SUMO_HOME>/docs/tutorial/manhattan directory._
This is not true, at least I can not find them there,

**Comment by angelobanse** [comment]
Download this [sumo-src-1.18.0.zip](https://sumo.dlr.de/releases/1.18.0/sumo-src-1.18.0.zip) or [sumo-win64extra-1.18.0.zip](https://sumo.dlr.de/releases/1.18.0/sumo-win64extra-1.18.0.zip) file. I just checked and the manhattan tutorial is there.

What did you download / where exactly did you searched?
